---
- hosts: all
  remote_user: bob

  vars:
    downloads_dir: ~/.ansible/downloads
    munitions_dir: ~/.ansible/munitions
    pyenv_dir: ~/.pyenv
    pythons:
      - { dir: ~/opt/python2, version: 2.7.18 }
      - { dir: ~/opt/python3, version: 3.7.9 }

  tasks:
    - name: Make downloads dir
      file:
        path: "{{ downloads_dir }}"
        state: directory

    - name: Make opt dir
      file:
        path: ~/opt/
        state: directory

    - name: Sync munitions
      synchronize:
        src: munitions/
        dest: "{{ munitions_dir }}"
        delete: yes
        recursive: yes

    - name: Get JDK15
      get_url:
        url: https://download.java.net/java/GA/jdk15.0.1/51f4f36ad4ef43e39d0dfdbaf6549e32/9/GPL/openjdk-15.0.1_linux-x64_bin.tar.gz
        dest: "{{ downloads_dir }}/jdk15.tar.gz"
        checksum: sha256:83ec3a7b1649a6b31e021cde1e58ab447b07fb8173489f27f427e731c89ed84a

    - name: Deploy JDK15
      unarchive:
        src: "{{ downloads_dir }}/jdk15.tar.gz"
        dest: ~/opt/
        remote_src: yes

    - name: Get pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ pyenv_dir }}"

    - name: Install Python
      shell:
        cmd: "{{ pyenv_dir }}/bin/pyenv install {{ item.version }}"
        creates: "{{ pyenv_dir }}/versions/{{ item.version }}"
      loop: "{{ pythons }}"

    - name: Symlink Python
      file:
        src: "{{ pyenv_dir }}/versions/{{ item.version }}"
        dest: "{{ item.dir }}"
        state: link
      loop: "{{ pythons }}"

    - name: Install Python deps
      pip:
        requirements: "{{ munitions_dir }}/requirements.txt"
        executable: "{{ item.dir }}/bin/pip"
      loop: "{{ pythons }}"

    # TODO - SSH keys
    # TODO - dot files
    # TODO - Afternoon Commander
    # TODO - crontabs

