---
- hosts: all

  vars:
    downloads_dir: ~/.ansible/downloads

    pyenv_dir: ~/.pyenv

    pythons:
      # - version: 2.7.18
      #   dir: ~/opt/python2

      - version: 3.7.9
        dir: ~/opt/python3

    jdks:
      # - version: 13.0.2
      #   url: https://download.java.net/java/GA/jdk13.0.2/d4173c853231432d94f001e99d882ca7/8/GPL/openjdk-13.0.2_linux-x64_bin.tar.gz
      #   sha256: acc7a6aabced44e62ec3b83e3b5959df2b1aa6b3d610d58ee45f0c21a7821a71

      - version: 15.0.1
        url: https://download.java.net/java/GA/jdk15.0.1/51f4f36ad4ef43e39d0dfdbaf6549e32/9/GPL/openjdk-15.0.1_linux-x64_bin.tar.gz
        sha256: 83ec3a7b1649a6b31e021cde1e58ab447b07fb8173489f27f427e731c89ed84a

  tasks:

    # --------------------- #
    # Basics
    # --------------------- #

    - name: Make downloads dir
      file:
        path: "{{ downloads_dir }}"
        state: directory

    - name: Make opt dir
      file:
        path: ~/opt/
        state: directory

    # --------------------- #
    # Config files
    # --------------------- #

    - name: Create dot files
      copy:
        src: munitions/{{ item }}
        dest: ~/
      loop:
        - .bash_profile
        - .bashrc

    # --------------------- #
    # Java
    # --------------------- #

    - name: Get JDK
      get_url:
        url: "{{ item.url }}"
        dest: "{{ downloads_dir }}/jdk{{ item.version }}.tar.gz"
        checksum: "sha256:{{ item.sha256 }}"
      loop: "{{ jdks }}"

    - name: Deploy JDK
      unarchive:
        src: "{{ downloads_dir }}/jdk{{ item.version }}.tar.gz"
        dest: ~/opt/
        remote_src: yes
      loop: "{{ jdks }}"

    # --------------------- #
    # Python
    # --------------------- #

    - name: Get pyenv
      git:
        repo: https://github.com/pyenv/pyenv.git
        dest: "{{ pyenv_dir }}"

    - name: Install Python
      shell:
        cmd: "{{ pyenv_dir }}/bin/pyenv install {{ item.version }}"
        creates: "{{ pyenv_dir }}/versions/{{ item.version }}/bin/python"
      loop: "{{ pythons }}"

    - name: Symlink Python
      file:
        src: "{{ pyenv_dir }}/versions/{{ item.version }}"
        dest: "{{ item.dir }}"
        state: link
      loop: "{{ pythons }}"

    - name: Install Python deps
      pip:
        executable: "{{ item.dir }}/bin/pip"
        name:
          - requests
          - pymysql
      loop: "{{ pythons }}"

    # --------------------- #
    # TODO
    # --------------------- #

    # TODO - SSH keys
    # TODO - Afternoon Commander
    # TODO - crontabs

